In [1]:

import pandas as pd
import tensorflow as tf
import numpy as np
from keras.preprocessing import image

Using TensorFlow backend.


In [3]:
data_test=pd.read_csv(r'C:\Users\Vishal\face_expression_recognition\fer2013_test_new1.csv')
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4144 entries, 0 to 4143
Data columns (total 4 columns):
Unnamed: 0    4059 non-null float64
emotion       4144 non-null int64
Usage1        4144 non-null object
pixels1       4144 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 129.6+ KB


In [50]:
del(b)

In [60]:
b=[]
for index ,row in data_test.iterrows():
    val=row['pixels1'].split(" ")
    for i in val:
        a=int(i)
        b.append(a)
arr=np.array(b,'float32')
x_test=arr.reshape(4144,2304)

In [61]:
x_test=x_test.reshape(4144,48,48,1)

In [10]:
import tensorflow as tf 
model1=tf.keras.models.load_model(r'C:\Users\Vishal\face_expression_recognition\modelface_network3.h5')        # network3
model2=tf.keras.models.load_model(r'C:\Users\Vishal\face_expression_recognition\modelface_network1.h5')         # network1
model3=tf.keras.models.load_model(r'C:\Users\Vishal\face_expression_recognition\modelface_network2.h5')         # network2

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [ ]:
#average probability

In [62]:
pred=[]
objects = ('angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral')
for i in range(0,4144):
    #p=[]
    p1=[]
    arr=x_test[i]
    arr = np.expand_dims(arr, axis = 0)
    arr/= 255
    custom1 = model1.predict(arr)
    #p.append(np.argmax(custom1))
    p1.append(custom1)
    custom2= model2.predict(arr)
    #p.append(np.argmax(custom2))
    p1.append(custom2)
    custom3= model3.predict(arr)
    #p.append(np.argmax(custom3))
    p1.append(custom3)
    #pred.append(s.mode(p))
    p1=np.array(p1)
    p1=p1.reshape(3,7)
    pred.append(np.argmax(p1.mean(axis=0)))

In [12]:
pred

[0,
 6,
 3,
 3,
 2,
 3,
 0,
 6,
 2,
 5,
 5,
 3,
 5,
 4,
 0,
 4,
 3,
 3,
 3,
 6,
 0,
 6,
 3,
 0,
 4,
 6,
 3,
 5,
 6,
 3,
 5,
 6,
 3,
 2,
 2,
 5,
 3,
 6,
 3,
 5,
 3,
 5,
 0,
 5,
 6,
 3,
 2,
 6,
 5,
 6,
 4,
 0,
 0,
 3,
 5,
 4,
 3,
 3,
 3,
 6,
 3,
 3,
 0,
 3,
 6,
 0,
 3,
 2,
 6,
 6,
 5,
 3,
 3,
 3,
 2,
 3,
 6,
 2,
 6,
 5,
 2,
 4,
 5,
 0,
 5,
 5,
 6,
 5,
 5,
 5,
 6,
 6,
 3,
 4,
 3,
 3,
 6,
 2,
 0,
 5,
 3,
 5,
 0,
 5,
 0,
 3,
 0,
 3,
 3,
 6,
 6,
 5,
 6,
 3,
 5,
 6,
 4,
 4,
 5,
 5,
 3,
 3,
 3,
 3,
 3,
 6,
 5,
 5,
 3,
 3,
 5,
 6,
 0,
 3,
 3,
 4,
 6,
 0,
 6,
 5,
 4,
 3,
 3,
 5,
 0,
 3,
 5,
 6,
 5,
 3,
 0,
 2,
 3,
 6,
 0,
 3,
 3,
 0,
 0,
 4,
 5,
 3,
 3,
 5,
 4,
 2,
 6,
 0,
 2,
 0,
 3,
 3,
 4,
 5,
 3,
 5,
 3,
 4,
 5,
 6,
 3,
 6,
 6,
 6,
 6,
 3,
 2,
 6,
 6,
 3,
 0,
 3,
 5,
 3,
 3,
 3,
 3,
 4,
 6,
 4,
 3,
 3,
 0,
 3,
 3,
 5,
 3,
 6,
 0,
 3,
 5,
 3,
 3,
 5,
 6,
 6,
 5,
 6,
 0,
 6,
 3,
 0,
 3,
 3,
 5,
 5,
 3,
 3,
 3,
 4,
 4,
 3,
 4,
 4,
 4,
 5,
 3,
 0,
 6,
 3,
 5,
 3,
 5,
 0,
 0,
 5,
 3,
 4,
 5,
 5,


In [134]:
len(pred)

4144

In [13]:
actual=np.array(data_test['emotion'].tolist(),'float32')

In [14]:
actual

array([0., 6., 3., ..., 1., 1., 1.], dtype=float32)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
objects = ['angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral']

In [17]:
actual=np.array(data_test['emotion'].tolist(),'float32')

In [18]:
confusion_matrix(actual,pred)

array([[ 439,   11,    6,   12,   25,    1,   14],
       [  18,   53,    5,    7,    2,    1,    3],
       [  12,    2,  146,    2,   28,   15,   12],
       [  24,    0,    8, 1358,   24,    5,   22],
       [  19,    0,   18,   23,  392,    4,   29],
       [   0,    0,   16,    5,    3,  627,    6],
       [  26,    0,    9,   21,   39,    7,  645]], dtype=int64)

In [19]:
print(classification_report(actual,pred,target_names=objects))

              precision    recall  f1-score   support

       angry       0.82      0.86      0.84       508
     disgust       0.80      0.60      0.68        89
        fear       0.70      0.67      0.69       217
       happy       0.95      0.94      0.95      1441
         sad       0.76      0.81      0.79       485
    surprise       0.95      0.95      0.95       657
     neutral       0.88      0.86      0.87       747

    accuracy                           0.88      4144
   macro avg       0.84      0.81      0.82      4144
weighted avg       0.88      0.88      0.88      4144



In [57]:
b=[]
for index ,row in data_test.iterrows():
    val=row['pixels1'].split(" ")
    for i in val:
        a=int(i)
        b.append(a)
arr=np.array(b,'float32')
x_test=arr.reshape(4144,2304)

In [58]:
x_test=x_test.reshape(4144,48,48,1)

In [25]:
import statistics as s

In [26]:
pred=[]
objects = ('angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral')
for i in range(0,4144):
    p=[]
    p1=[]
    arr=x_test[i]
    arr = np.expand_dims(arr, axis = 0)
    arr/= 255
    custom1 = model1.predict(arr)
    p.append(np.argmax(custom1))
    p1.append(custom1)
    custom2= model2.predict(arr)
    p.append(np.argmax(custom2))
    p1.append(custom2)
    custom3= model3.predict(arr)
    p.append(np.argmax(custom3))
    p1.append(custom3)
    p1=np.array(p1)
    p1=p1.reshape(3,7)
    try:
        pred.append(s.mode(p))
    except:
        pred.append(np.argmax(p1.mean(axis=0)))

In [27]:
pred

[0,
 6,
 3,
 3,
 2,
 3,
 0,
 6,
 2,
 5,
 5,
 3,
 5,
 4,
 0,
 4,
 3,
 3,
 3,
 6,
 0,
 6,
 3,
 0,
 4,
 6,
 3,
 5,
 6,
 3,
 5,
 6,
 3,
 2,
 2,
 5,
 3,
 6,
 5,
 5,
 3,
 5,
 0,
 5,
 4,
 3,
 2,
 6,
 5,
 6,
 4,
 0,
 0,
 3,
 5,
 4,
 3,
 3,
 3,
 6,
 3,
 3,
 0,
 3,
 6,
 0,
 3,
 2,
 6,
 6,
 5,
 3,
 3,
 3,
 2,
 3,
 6,
 2,
 6,
 5,
 2,
 4,
 5,
 0,
 5,
 5,
 6,
 5,
 5,
 5,
 6,
 6,
 3,
 4,
 3,
 3,
 6,
 2,
 0,
 5,
 3,
 5,
 0,
 5,
 0,
 3,
 0,
 3,
 3,
 6,
 6,
 5,
 6,
 3,
 5,
 6,
 4,
 4,
 5,
 5,
 3,
 3,
 3,
 3,
 3,
 6,
 5,
 5,
 3,
 3,
 5,
 6,
 0,
 3,
 3,
 4,
 6,
 0,
 6,
 5,
 4,
 3,
 3,
 5,
 0,
 3,
 5,
 6,
 5,
 3,
 0,
 2,
 3,
 6,
 0,
 3,
 3,
 0,
 0,
 4,
 5,
 3,
 3,
 5,
 4,
 2,
 6,
 0,
 2,
 0,
 3,
 3,
 4,
 5,
 3,
 5,
 3,
 4,
 5,
 6,
 3,
 6,
 6,
 6,
 6,
 3,
 2,
 6,
 6,
 3,
 0,
 3,
 5,
 3,
 3,
 3,
 3,
 4,
 6,
 4,
 3,
 3,
 0,
 3,
 3,
 5,
 3,
 6,
 0,
 3,
 5,
 3,
 3,
 5,
 6,
 6,
 5,
 6,
 0,
 6,
 3,
 0,
 3,
 3,
 5,
 5,
 3,
 3,
 3,
 4,
 4,
 3,
 4,
 4,
 4,
 5,
 3,
 0,
 6,
 3,
 5,
 3,
 5,
 0,
 0,
 5,
 3,
 4,
 5,
 5,


In [28]:
CM=confusion_matrix(actual,pred)
CM

array([[ 438,   11,    7,   12,   25,    1,   14],
       [  19,   52,    5,    7,    2,    1,    3],
       [  13,    1,  143,    3,   30,   15,   12],
       [  24,    1,    8, 1356,   24,    6,   22],
       [  20,    0,   18,   23,  390,    4,   30],
       [   0,    0,   16,    5,    3,  627,    6],
       [  26,    0,    9,   21,   43,    7,  641]], dtype=int64)

In [29]:
print(classification_report(actual,pred,target_names=objects))

              precision    recall  f1-score   support

       angry       0.81      0.86      0.84       508
     disgust       0.80      0.58      0.68        89
        fear       0.69      0.66      0.68       217
       happy       0.95      0.94      0.95      1441
         sad       0.75      0.80      0.78       485
    surprise       0.95      0.95      0.95       657
     neutral       0.88      0.86      0.87       747

    accuracy                           0.88      4144
   macro avg       0.83      0.81      0.82      4144
weighted avg       0.88      0.88      0.88      4144



In [53]:
pred1=[] # network1
objects = ('angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral')
for i in range(0,4144):
    arr=x_test[i]
    arr = np.expand_dims(arr, axis = 0)
    arr/= 255
    custom1 = model1.predict(arr)
    pred1.append(np.argmax(custom1))

In [56]:
pred2=[]  # network2
objects = ('angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral')
for i in range(0,4144):
    arr=x_test[i]
    arr = np.expand_dims(arr, axis = 0)
    arr/= 255
    custom1 = model3.predict(arr)
    pred2.append(np.argmax(custom1))

In [59]:
pred3=[]
objects = ('angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral')
for i in range(0,4144):
    arr=x_test[i]
    arr = np.expand_dims(arr, axis = 0)
    arr/= 255
    custom1 = model1.predict(arr)
    pred3.append(np.argmax(custom1))

In [63]:
d=pd.DataFrame()
d['actual']=[int(actual[i]) for i in range(4144)]
d['preddicted_network1']=pred1
d['preddicted_network2']=pred2
d['preddicted_network3']=pred3
d['predicted_ensemble']=pred

In [64]:
d

actual  preddicted_network1  preddicted_network2  preddicted_network3  \
0          0                    2                    0                    2   
1          6                    6                    6                    6   
2          3                    3                    3                    3   
3          3                    3                    3                    3   
4          2                    2                    2                    2   
...      ...                  ...                  ...                  ...   
4139       1                    0                    1                    0   
4140       1                    1                    1                    1   
4141       1                    1                    1                    1   
4142       1                    0                    0                    0   
4143       1                    1                    1                    1   

      predicted_ensemble  
0                      0  
1                      6  
2                      3  
3                      3  
4                      2  
...                  ...  
4139                   1  
4140                   1  
4141                   1  
4142                   0  
4143                   1  

[4144 rows x 5 columns]

In [66]:
d.to_csv(r'C:\Users\Vishal\face_expression_recognition\Test_submission.csv')